spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blog
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
springdoc:
  packages-to-scan: com.guardjo.simpleblogfinder.controller
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /api-docs/data
    groups:
      enabled: true
  cache:
    disabled: true
search-api-key : ${KAKAO_REST_API_KEY}